### ISSUE TITLE
"'SearchVideos' object has no attribute 'page'" error on android kivy project

### ISSUE THREAD

**Issue by hakanb78** [alexmercerind/youtube-search-python#12]
I'm trying to use the module on a kivy app but it generates "'SearchVideos' object has no attribute 'page'" error. On buildozer.spec i use 'youtube-search-python' as the module name to import.

**Comment by alexmercerind** [comment]
It is a **network error**. Ensure you have proper internet connection.
(Typically the library is supposed to return None in case of it, I'll fix that in next release.)

The library is working fine. You can confirm it by running it on another machine or environment.

Thankyou!

**Comment by alexmercerind** [comment]
@hakanb78 Feel free to reopen issue in case you feel it.

**Comment by hakanb78** [comment]
Hi, thank you for your answer. I checked the network connection of the mobile device and it's fine. Also the app can do other network related operations without any problem. Same code works fine on linux environment but i keep getting this same error on android.

**Comment by alexmercerind** [comment]
Hi @hakanb78 !

Since this project only uses pre-installed Python 3 libraries (no third party modules), which include:

- html
- urllib
- json

You should ensure that these are installed in your Kivy Android environment.

You can check new release with:
```
pip3 install youtube-search-python==1.2.5
```
If the new release response returns None, then it is definitely a network error.

Hope it helps you.
Feel free to leave feedback!

Thankyou.
