### ISSUE TITLE
Regression: Cannot retrieve upload_date or publish_date

### ISSUE THREAD

**Issue by Zocker1999NET** [alexmercerind/youtube-search-python#144]
By using following script and `git bisect start && git bisect good v1.5.1 && git bisect bad main && git bisect run ./check.py`, I found that the commit 31dfb19 introduced this regression:
```python3
#!/usr/bin/env python3
import sys
from youtubesearchpython import Video

info = Video.getInfo("https://www.youtube.com/watch?v=9eQfJqWLXwY") # example video which is quite new
sys.exit(0 if (info.get("uploadDate") or info.get("publishDate")) is not None else 1)
```

The commit 31dfb19 was introduced by PR #142, which fixed #134. In the PR, the author stated YouTube suddenly does not give this information in a common way. However older versions of youtubesearchpython can still extract these dates, even on newer videos.

I really don't know how to fix this while keeping the fix for #134, but maybe this information is helpful to someone else

**Comment by mytja** [comment]
Indeed, I know about that since #142 
Problem comes from commit [59ce6b12f0546a1d69b3a6d34500220951a588fc](https://github.com/alexmercerind/youtube-search-python/commit/59ce6b12f0546a1d69b3a6d34500220951a588fc), where I migrated from HTML parsing to InnerTube API. For some reason, the InnerTube API comes without publish_date & upload_date. If we'd use HTML parsing, StreamURLFetcher wouldn't work. I could add it using another request to HTML & parse it, but that's very very unoptimal, so I'm thinking of adding another variable to Video class, for example `useHTML`, which would default to false.
