### ISSUE TITLE
Download playlist

### ISSUE THREAD

**Issue by cumulus13** [alexmercerind/youtube-search-python#26]
how to download or get video url from youtube url playlist with this module ?

**Comment by alexmercerind** [comment]
Hi @cumulus13,
Initially this project supported searching videos only. Later on, another person requested to add playlist search, so I added it. 
In my personal project, I just use ```SearchVideos``` class. 
Few days ago, you can see an improvement PR to playlist search from @akshay-movieverse.

For this project, as the name says, it is just a library to only "Searching in YouTube", so the feature you requested is kind of **beyond the scope of this project**  as, videos present in the playlist are not present in the HTML of the result page. 
So, there is no way for me to add videos in a playlist without making an extra GET request.


**What you can do?**
- Since, this project just provides search functionality & isn't a complete alternative to official YouTube API v3, you can use their API itself to get the videos in a playlist by passing video ID from this library (using this library will definitely save you some number of requests on Google).
- Search for any other project. Which is more specific in dealing with YouTube playlists.
- Make PR to this project, I can mention you in the project credits if you wish.

I'm a sole maintainer & this project promises that, it does not use any third party library, so it is kind of difficult to add/maintain features as YouTube likes to change stuff randomly. 

Thankyou.

**Comment by JAXPARROW** [comment]
from the search_result is there a way i can access only individuals items, let's say title and link so i can process them further into my custom function?

**Comment by alexmercerind** [comment]
I'm closing this. Let's see, if I plan to improve playlist search results.

**Comment by alexmercerind** [comment]
Hi there @cumulus13 !

This functionality is finally added to the library.

You may checkout if that helps you now.
