### ISSUE TITLE
Include upload date in search results? (enhancement)

### ISSUE THREAD

**Issue by tobip** [alexmercerind/youtube-search-python#29]
Hi,
I love your search script and have an enhancement request:
Could you include the upload date from the search results into the query?
Where it says `1 year ago`, `3 months ago` etc.?
I hope this would not be too much difficulties and it would be a great enhancement for me :-)

**Comment by alexmercerind** [comment]
Hi @tobip 👋!

Now, after alexmercerind@410142a4f43e641979e86fd25d36e112d54877af commit,  the result will contain a key with the name "publishTime", which contains your required information.

```json
{
    "search_result": [
        {
            "index": 0,
            "id": "K4DyBUG242c",
            "link": "https://www.youtube.com/watch?v=K4DyBUG242c",
            "title": "Cartoon - On & On (feat. Daniel Levi) [NCS Release]",
            "channel": "NoCopyrightSounds",
            "duration": "3:28",
            "views": 380399566,
            "thumbnails": [
                "https://img.youtube.com/vi/K4DyBUG242c/default.jpg",
                "https://img.youtube.com/vi/K4DyBUG242c/hqdefault.jpg",
                "https://img.youtube.com/vi/K4DyBUG242c/mqdefault.jpg",
                "https://img.youtube.com/vi/K4DyBUG242c/sddefault.jpg",
                "https://img.youtube.com/vi/K4DyBUG242c/maxresdefault.jpg"
            ],
            "channelId": "UC_aEa8K-EOJ3D6gOs7HcyNg",
            "publishTime": "5 years ago"
        }
```

Feel free to test yourself & leave feedback.

**Comment by tobip** [comment]
Awesome, works like a charm!
Thanks a lot :-)

**Comment by tobip** [comment]
Hi, unfortunately sometimes I get an error like this:
`videos__search.py, line 76, in result
    "publishTime": self.publishTime[index],
IndexError: list index out of range`

For example, when I search for `awesome tunes`:
`SearchVideos('awesome tunes', offset=1, mode='dict', max_results=20).result()`

**Comment by alexmercerind** [comment]
Hi @tobip!

Please check the things now. They should be alright.

Thanks for telling me about this.

**Comment by tobip** [comment]
I tried, and the error seems to persist...

**Comment by alexmercerind** [comment]
@tobip ... Can you make a PR with a fix for that, I'm unable to reproduce it.

**Comment by tobip** [comment]
So for some reason the script running through `self.pageSource[index]` just ends before it can find the last `publishTime` entry.
My workaround is to limit my search to 19 items instead of 20, that way it works for me.

**Comment by raitonoberu** [comment]
I can reproduce it.
`SearchVideos('awesome tunes', offset=1, mode='dict', max_results=20).result()` raises the same exception as above. I don't really know what's going on, but if I try to find "publishedTimeText":{"simpleText" in the page content, it only finds 19 times.

Page content: https://pastebin.com/9uVCSHbB

**Comment by raitonoberu** [comment]
![image](https://user-images.githubusercontent.com/64320078/98276717-f9374000-1fc8-11eb-9158-c721922f4c64.png)
I've found the problem! The stream has no publish time

**Comment by alexmercerind** [comment]
Yeah these live videos mess up a lot... That's why the script is differently written for adding views & duration of a video too.

Thanks a lot for finding the problem @raitonoberu.

For the exact same reason... the script keeps views & duration as "LIVE" initially & modify them later on in case the video isn't live. I have to do something similar for publish time. e.g.

**Initially keeping views & duration "LIVE"**
https://github.com/alexmercerind/youtube-search-python/blob/2c0159c46cdbf0241d0831e08ec465e0002d3d48/youtubesearchpython/videos__scripthandler.py#L64-L65

**Changing the value if the video isn't live**
https://github.com/alexmercerind/youtube-search-python/blob/2c0159c46cdbf0241d0831e08ec465e0002d3d48/youtubesearchpython/videos__scripthandler.py#L34-L35
 
Same approach can be used for publish time. Let's see what can I do.

**Comment by alexmercerind** [comment]
Okay this same logic worked yet again.
