### ISSUE TITLE
More options ? order by time ? limit time?in one month?

### ISSUE THREAD

**Issue by makelove** [alexmercerind/youtube-search-python#32]
```
search = SearchVideos(kw, offset = 1, mode = "json", max_results = 10)
self.searchPreferences = "EgIQAQ%3D%3D"
```
searchPreferences cann't be fixed
should add to parameters
then I don't need to change source code

Thank you

**Comment by makelove** [comment]
Question 2:
search.result() don't have publishTime

why ?

**Comment by alexmercerind** [comment]
Hello @makelove!

1. I understand what you are saying & I'll try to add different searchPreferences for user to use. This can be a really good enhancement.
2. You don't have "publishTime" because, you possibly installed using pip & the version on the PyPI wasn't updated (because of stability & due testing). Please use the module from master of GitHub, then you'll be able to get  "publishTime". I'll soon update PyPI version of youtube-search-python.

**Comment by alexmercerind** [comment]
> Question 2:
> search.result() don't have publishTime
> 
> why ?

@makelove Now you can update to version 1.3.2 using following command to get "publishTime"
```
pip3 install youtube-search-python==1.3.2
```

**Comment by tobip** [comment]
Hi, 
I was just about to ask for the same: order by and other search options would be a great additional feature to have and I think it would fit well to the set of already available features.
Looking forward to new updates :-)

**Comment by alexmercerind** [comment]
Hi there everyone!
It's cool that people are using this library & it is completing their requirements. Thanks for your love & support.
I also look forward to add this feature soon, but I have discovered a more efficient way of fetching search results, both in terms of maintaining & adding new features to this project.
Right now, I'm just fixing the bugs that occur in this project. Since, development of this library is dependent on the amount of free time I have, it's kinda hard for me nowadays to write code because of busy schedule. 
I'll soon be adding not just this feature, along with many others, and will be doing rewrite to make things more efficient. 

Greetings! 🍀

**Comment by shekharchander** [comment]
@makelove If you are eager to try filters, you can use searchtube. It has all the features you need. htttps://github.com/shekharchander/searchtube

**Comment by alexmercerind** [comment]
You guys may checkout the "new" youtube-search-python in [development] branch.

**Major additions and improvements are**

- Now the search result contains a lot lot more information than before.
- Now you can now perform a "general search" on YouTube i.e. to get all types of results like videos, playlists & channels at once (like a generic result from YouTube is). Earlier you could just search for playlist or videos at a time, now you can search for all at the same time.
- Now you can search for channels.
- Now you can perform custom searches using ```SearchCustom``` class. (this closes this issue).
- I have made the code a lot more maintainable & easier for users to understand.

Since, this new branch adds a lot of new features, it introduces many breaking changes at the moment. I'll still try to keep old classes to keep giving legacy support.
Thankyou!
