### ISSUE TITLE
Error if the youtube link is unvailable

### ISSUE THREAD

**Issue by Darkempire78** [alexmercerind/youtube-search-python#46]
```Python
video = Video.get(link, mode = ResultMode.json)
print(video)
```
If we give an unvailable link, it returns an error.

![image](https://user-images.githubusercontent.com/50015928/104717668-f3c54700-5729-11eb-9f1a-c7fc6e43cd84.png)

**Comment by alexmercerind** [comment]
Hi @Darkempire78 !

I've marked this issue as enhancement, because I don't see a reason behind why one is passing an "unavailable link".

**You can make use of "try except" to deal with this I believe.** 
Should I raise some another exception according to your requirement?

What I can do on my behalf is add another fancy exception. Still you have to do "try except" stuff.
Let me know, if I misunderstood you or give me bit information like how you want it function in such case.

Greetings! 🍀

**Comment by Darkempire78** [comment]
Currently I use a try/except sytem, but i think that return None is better than return an error.
I use this code to check if th link exist, perhaps there is another system ?

**Comment by alexmercerind** [comment]
Hi @Darkempire78,

I hope latest commits make improvements for you.

Have a good day.
