### ISSUE TITLE
Making the requests async?

### ISSUE THREAD

**Issue by Pectacius** [alexmercerind/youtube-search-python#48]
Wonder if the `RequestHandler` could be made async by using something like aiohttp instead of urllib.requests? I'm using this package in some app and I would like to do stuff like make more requests while I'm waiting for the response of the first request.

**Comment by alexmercerind** [comment]
Hi there @Pectacius !

I myself look forward for geeting asynchronous support in this library.

But as this project promises two things, there are challenges for me:
- **Keeping legacy support**
  - No matter how much rewrite or new classes & methods I add or modify, I always try to keep old things working because I don't want to break code of other people.
- **Library promises to use no third party library**
  - It's unfortunate we don't have any asynchronous networking stuff in standard library of Python.

I'll try to use httpx & get things as you wished.
Greetings.

**Comment by Pectacius** [comment]
That is great! I'll be looking forward to that. In the meantime, I will probably use a decent amount of the existing code that this library already has and tweak it a bit with another library to create a temporary solution for async requests for my app.

**Comment by alexmercerind** [comment]
Hi there @Pectacius !

I'm done adding the asynchronous support to this project.

AND... It's substantially faster than the older version. Python's urllib seems really dated. I LITERALLY CAN VISIBLY SEE THE DIFFERENCE.

🎉 Please checkout [here](https://github.com/alexmercerind/youtube-search-python/tree/main/youtubesearchpython/__future__).

You may run [this](https://github.com/alexmercerind/youtube-search-python/blob/main/asyncExample.py) test script to see the async version functioning.

Let me know what do you think. Any bugs you discover or any changes you wanna see...

Thankyou.
Sorry I got late. School sucks.
