### ISSUE TITLE
How to get playlist information using link?

### ISSUE THREAD

**Issue by markegor** [alexmercerind/youtube-search-python#52]
Hello! I'm excited with your project, because it really simple, quickly and powerful, but i found a small bug. I think when **playlist's ID** includes underscore or dash then _PlaylistsSearch_ doesn't work properly. 
For example: when i try to find this playlist: 
'https://www.youtube.com/playlist?list=PLrxcNWZXdQ2nRZvJcLoQpJhUBrPVOBbll' - it works perfectly, but when i try find this one:
'https://youtube.com/playlist?list=OLAK5uy_nHcJWdK2mi8vKVRco3MfQuH12938KF-hQ' or 
'https://www.youtube.com/playlist?list=OLAK5uy_mRdEfaPOzXui_tyud3VE_vAHDqCiPOyDw' - i have no results =(

Can you fix it PLEASE ?)

**Comment by alexmercerind** [comment]
Hi there!
Nice to meet you, I appreciate your feedback for the library.

First of all, if you are not aware that `PlaylistsSearch` should be used to search for playlists i.e. by passing search query (not link).

As you are "searching" with the link itself, so that confuses YouTube itself.
So, I assume what you're trying to do is to get playlist information (i.e. videos etc. in it) using its link. If I got your problem correctly, then searching probably isn't the best solution. And there isn't any functionality to get playlist information using link in this library yet (like `Video.get`).

If you want, I can try to implement something like `Playlist.get(<link>)` to get playlist information using its link.

For playlist https://youtube.com/playlist?list=OLAK5uy_nHcJWdK2mi8vKVRco3MfQuH12938KF-hQ:
[This](https://www.youtube.com/results?search_query=https%3A%2F%2Fyoutube.com%2Fplaylist%3Flist%3DOLAK5uy_nHcJWdK2mi8vKVRco3MfQuH12938KF-hQ&sp=EgIQAw%253D%253D) result is shown.

For playlist 'https://www.youtube.com/playlist?list=OLAK5uy_mRdEfaPOzXui_tyud3VE_vAHDqCiPOyDw:
[This](https://www.youtube.com/playlist?list=OLAK5uy_mRdEfaPOzXui_tyud3VE_vAHDqCiPOyDw) playlist is shown.

You may confirm yourself that both pages show `No results found`, so there is nothing on my part that I can do.

Thankyou.
Let me know.

**Comment by markegor** [comment]
I got it, Thanks for answer! I really want to be able to use something like "Playlist.get (<playlist-link>)" in the near future. Can you implement it please ?)

**Comment by markegor** [comment]
Hi again 👋🏽! Can you say how soon you will make **"Playlist.get ()"** and is it even possible? Thanks for the answer 🙏🏽)

**Comment by alexmercerind** [comment]
Hey there!

`Playlist` class is here, to get playlist information using link.

It has three methods:

- `get` to get all the information about playlist.
- `getInfo` to get only information.
- `getVideos` to get videos in the playlist.

Thankyou.

I know, I'm late.
I had a busy schedule this week.

[Here](https://github.com/alexmercerind/youtube-search-python#getting-playlist-information-using-link) are few examples to help you.

And if you really like the project, consider supporting it.

**Comment by alexmercerind** [comment]
> Hi again 👋🏽! Can you say how soon you will make "Playlist.get ()" and is it even possible? Thanks for the answer 🙏🏽)

It took me time to figure out the way. Sorry for the delay.

**Comment by alexmercerind** [comment]
@markegor,

Get the latest version with:
```
pip3 install youtube-search-python==1.4.1
```
