### ISSUE TITLE
'CustomSearch' object has no attribute 'getShelfComponent'

### ISSUE THREAD

**Issue by jacksonw765** [alexmercerind/youtube-search-python#53]
`CustomSearch(search, searchPreferences=VideoUploadDateFilter.today).result()`
I am running a custom search and every 10 queries or so it fails with this error. 

`'CustomSearch' object has no attribute 'getShelfComponent'`

**Comment by alexmercerind** [comment]
Thanks for the report!

Random issues occurring due to changes from YouTube, is not a new thing for this project.

Looking for fixes.

**Comment by alexmercerind** [comment]
Hi there @jacksonw765!

I'm unable to reproduce the mentioned issue so far. 
I've performed 50 searches in sequence, using `CustomSearch` class exactly same as you & none of them failed.

Please ensure you're using the latest version.
If you are using latest version, I'll let this issue stay opened, otherwise please provide me more information.

Have a great day.

**Comment by jacksonw765** [comment]
I am using a mix of searchPreferences, it does not happen often but when it does it is skewing the results. Just something to keep in mind.

**Comment by alexmercerind** [comment]
Comes out these were just few typos & an await missing in async version.
Fixed now.
