### ISSUE TITLE
Terms of service abuse

### ISSUE THREAD

**Issue by Julien00859** [alexmercerind/youtube-search-python#7]
Citing the terms of service available here: https://www.youtube.com/static?gl=GB&template=terms

> **Permissions and Restrictions**
> 
> You may access and use the Service as made available to you, as long as you comply with this Agreement and the law. You may view or listen to Content for your personal, non-commercial use. You may also show YouTube videos through the embeddable YouTube player.
> 
> The following restrictions apply to your use of the Service. You are not allowed to:
> 
> [...]
>
> access the Service using any automated means (such as robots, botnets or scrapers) except: (a) in the case of public search engines, in accordance with YouTube’s robots.txt file; (b) with YouTube’s prior written permission; or (c) as permitted by applicable law;

The project advertise itself as a library to "*search videos in YouTube WITHOUT using YouTube Data API v3.*" and is indeed a scrapper of the youtube web interface. This is a clear abuse of the terms cited above and prevent your library from working in various controlled environment.

The problematic code is as follow:

https://github.com/alexmercerind/youtube-search-python/blob/8b5cdfab54980b958cc6c3a4dfecf5c2d013b845/youtubesearchpython/requesthandler.py#L10-L14

**Comment by alexmercerind** [comment]
Everyone knows that this library is based on web scraping.
 
We can clearly observe that the usage of YouTube website in this library is counted as "You may view or listen to Content for your personal, non-commercial use", which obviously is correct, as this library is for personal use (I cannot restrict people what they are doing with this library, like other projects as [youtube-dl](https://github.com/ytdl-org/youtube-dl) also cannot.) and neither I'm making any commercial usage of this library (being fully open source on GitHub, it is your own choice to use it or not).

Further read [this](https://parsers.me/us-court-fully-legalized-website-scraping-and-technically-prohibited-it/) law article about web-scraping, which simply sums up to be, a web crawler would be allowed to search YouTube for video titles, but it could not re-post the YouTube videos on its own site, since the videos are copyrighted. And YouTube terms and condition site states:

```
The following restrictions apply to your use of the Service. You are not allowed to:
access, reproduce, download, distribute, transmit, broadcast, display, sell, license, alter, modify or otherwise use any part of the Service or any Content except: (a) as specifically permitted by the Service;  (b) with prior written permission from YouTube and, if applicable, the respective rights holders; or (c) as permitted by applicable law
``` 
(The point (c) allows everyone to do so.)

And I recommend you to open similar issue to other projects like:
[youtube-dl](https://github.com/ytdl-org/youtube-dl)
[youtube_search](https://github.com/joetats/youtube_search)
[fast-youtube-search](https://github.com/andrscyv/fast_youtube_search)

If projects older than this library exist still on GitHub, then it certainly means that those projects are legal to exist, and so does this project.

This does not do abuse of YouTube website, neither this library is "automated", the library is used to search on user's wish.
It is the choice of the user if he automates it, which he/she can already do even with WebDrivers and things like selenium, for various browsers out there.

Thankyou!
