### ISSUE TITLE
Support for finding Playlists

### ISSUE THREAD

**Issue by betatester899** [alexmercerind/youtube-search-python#9]
Hey, first of all, thanks your module works great and it does the job.

Would it be possible to add support for finding for playlists (links) on Youtube?

And maybe add an option so you can define what kind of search results should be included (normal video, livestream, playlist).

Right now I just search for the video and then see if duration = "LIVE" or not, to determine this, but it would be cool if you have a built in function.

Best regards.

**Comment by alexmercerind** [comment]
Thankyou for your positive feedback.

I can definitely try to add support for playlist search, but I cannot guarantee that I'll be able to. I'll try to add it in the next release.
What the problem is the fact that, YouTube likes to mess a lot with its website time to time. The challenge upon me is to keep fixing the already added features.
The library does not use any third party library like requests or BeautifulSoup, so it takes time to manage the stuff. 

I can remove the LIVE videos from result, the same way you are doing it, but it will add one more loop before returning the result.
And YouTube itself shows live videos in the "videos only" filter, so I did not change it. The users are themselves supposed to sort it, at this point at least.

**Comment by betatester899** [comment]
Hey Alex

I appreciate your effort. I have been maintaining a project that used the Youtube API, but unfortunately Google made it impossible for me to keep using the API, so I know how hard it is to maintain these „workaround“ solutions. I am happy for the effort you put in it to adapt to the changing youtube environment.

Best Regards

**Comment by alexmercerind** [comment]
Hi there!

Check the new release on PyPI with:
```
pip3 install youtube-search-python==1.2.4
```

Playlist search is added now.
Or clone the master. 
Let me know, if you find any problem.

Thankyou!
